### ISSUE TITLE
WShEx meta-issue - Roadmap and other features

### ISSUE THREAD

**Issue by labra** [weso/WShEx#1]
# WShEx meta-issue

# Roadmap
We expect to deliver the following artifacts

- [X] WShEx paper: Submitted and accepted at Wikidata workshop 2022. Preprint available at: https://arxiv.org/abs/2208.02697
- [ ] WShEx examples: Some examples appear at the specification page
- [ ] WShEx grammar. Pending...we still need to add some features.
- [ ] WShEx formal specification. A first draft of a simplified language appears in the paper. 
- [ ] WShEx implementations. First implementation is part of [shex-s](https://github.com/weso/shex-s/tree/master/modules/wshex)

# Features
- [X] Labels, descriptions, aliases
- [X] Statements and triple constraints
- [ ] Built-in datatypes
- [X] Qualifiers
- [ ] References
- [ ] Sitelinks
